# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20160527_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
