# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_repo_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linter', models.TextField()),
                ('output', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='build',
            old_name='result',
            new_name='result_old',
        ),
        migrations.AlterField(
            model_name='build',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='interface.Repo'),
        ),
        migrations.AddField(
            model_name='result',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='interface.Build'),
        ),
    ]
