# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 05:49
from __future__ import unicode_literals

from django.db import migrations


def pep8_to_pycodestyle(apps, schema_editor):
    Result = apps.get_model('interface', 'Result')
    Result.objects.filter(linter='PEP8').update(linter='pycodestyle')


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_remove_build_result_old'),
    ]

    operations = [
        migrations.RunPython(pep8_to_pycodestyle),
    ]
