# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 01:49
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('interface', '0011_auto_20160530_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='repo',
            name='full_name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='interface.UserProxy'),
        ),
        migrations.AlterField(
            model_name='result',
            name='linter',
            field=models.TextField(choices=[(b'pycodestyle', b'pycodestyle'), (b'eslint', b'eslint')]),
        ),
    ]
