# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_auto_20160624_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='default_branch',
            field=models.TextField(default='master'),
        ),
        migrations.AddField(
            model_name='repo',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='build',
            name='status',
            field=models.TextField(choices=[('success', 'success'), ('error', 'error'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending'),
        ),
        migrations.AlterField(
            model_name='result',
            name='linter',
            field=models.TextField(choices=[('pycodestyle', 'pycodestyle'), ('npm_lint', 'NPM Lint')]),
        ),
    ]
